### ISSUE TITLE
Pass in a browserify instance

### ISSUE THREAD

**Issue by ajoslin** [bendrucker/bundleify#1]
Instead of accepting options, allow passing in a browserify instance.

Right now, I can't run global transforms or plugins on the final bundle, since they can't be defined from package.json.

Something like this seems like it would work:

``` js
function build (options, callback) {
  var bundle = browserify({debug: true})
    .transform(myTransform, {global: true})
    .plugin(myPlugin)

  return bundleify(bundle, options, done)
}
```

Thoughts?

**Comment by bendrucker** [comment]
Decided on `options.plugins`. A browserify plugin is just a function that receives the instance and some defined options. You can register transforms in there or use prebuilt plugins.
