### ISSUE TITLE
Enable ES2020 (tiny ES6 subset)

### ISSUE THREAD

**Issue by bendrucker** [bendrucker/bundleify#2]
- [Arrow functions are unsupported in Safari and IE, all versions](http://caniuse.com/#feat=arrow-functions&search=arrow)
- [Template literals aren't supported until iOS 9](http://kangax.github.io/compat-table/es6/#test-template_literals)
- [`const` has function scope instead of block in Safari which could cause weirdness](http://caniuse.com/#feat=const)

These are the features of ES6 I use anyway in stuff I only expect to run in Node or Chrome, e.g. test suites. 

The version of es2020 would be `~1.0.1`, so no new syntax would be supported without a minor release of bundleify. No syntax would be disabled for transpilation without a major version bump.

Thoughts @ajoslin @chrisinajar @ahdinosaur? Are these defaults helpful or do you guys configure syntax support on a per-project basis?

**Comment by ajoslin** [comment]
I currently use my own set of babel plugins: basically what's in ES2020 plus object (de)structuring. 

I'd say :+1: for adding ES2020, more cool defaults. It doesn't break anything.

The only downside would be it adds opinions that someone might not use -- eg someone using Typescript has no use for Babel plugins. But I don't think that's a real issue.

**Comment by bendrucker** [comment]
Blocked by https://github.com/yoshuawuyts/es2020/issues/5
